module.exports = { name: "vine", run(client, msg, args) {
  var options = ["https://www.youtube.com/watch?v=CqCCBohjaqA", "https://www.youtube.com/watch?v=rNEINbvGEro", 
  "https://www.youtube.com/watch?v=tjgaOPsbZdY", "https://www.youtube.com/watch?v=psBwRVd2Zfg", "https://www.youtube.com/watch?v=yVNtFUqXD-Q", 
  "https://www.youtube.com/watch?v=kZSfPPJ4Fk8", "https://www.youtube.com/watch?v=6AYv6rV3NXE", "https://www.youtube.com/watch?v=2bnnDTPCA94f", 
  "https://www.youtube.com/watch?v=vGLsUg161fI", "https://www.youtube.com/watch?v=xxh-idQcKzE", "https://www.youtube.com/watch?v=21jLmc_Il3o", 
  "https://www.youtube.com/watch?v=FQQ1kIbKnms", "https://www.youtube.com/watch?v=LTr7XiqfJcU", "https://www.youtube.com/watch?v=VpNp0zTGEfM", 
  "https://www.youtube.com/watch?v=EcLPNGLRHU8", "https://www.youtube.com/watch?v=UTC4gMxivII", "https://www.youtube.com/watch?v=5yxzeeacVuE", 
  "https://www.youtube.com/watch?v=6wmOnldmKQI", "https://www.youtube.com/watch?v=ejE2wWvjTx8", "https://www.youtube.com/watch?v=1Yy2kI70glc", 
  "https://www.youtube.com/watch?v=4PRbjMEwBBk", "https://www.youtube.com/watch?v=9NkkZJHova4", "https://www.youtube.com/watch?v=R5J7znTWijg", 
  "https://youtu.be/SBeYzoQPbu8", "https://youtu.be/aRsWk4JZa5k", "https://youtu.be/DaXYaiyqGd0", "https://youtu.be/h232bilq8eQ", 
  "https://www.youtube.com/watch?v=37LNH5foeUU", "https://www.youtube.com/watch?v=iZlpsneDGBQ", "https://www.youtube.com/watch?v=KpUWQVx1PnU", 
  "https://youtu.be/ZJNEB9lHtk0","https://www.youtube.com/watch?v=VP5kC9fJAUE", "https://www.youtube.com/watch?v=DaM6Pqyk48s", 
  "https://www.youtube.com/watch?v=5rjDNVKoDVo", "https://www.youtube.com/watch?v=ooEAm7L-sGI", "https://www.youtube.com/watch?v=ZARc4TGjL7A", 
  "https://www.youtube.com/watch?v=XUjTmTnnszk", "https://www.youtube.com/watch?v=GaNGKD4MTV0", "https://www.youtube.com/watch?v=LJ201maI8e4", 
  "https://www.youtube.com/watch?v=ZeIr0FVJwGs", "https://www.youtube.com/watch?v=Y8ymOt62H1o", "https://www.youtube.com/watch?v=x9oATmqIr0I", 
  "https://www.youtube.com/watch?v=enH0Tp4L3Dk", "https://www.youtube.com/watch?v=EwAajOtfNT8", "https://www.youtube.com/watch?v=T-McS-shPz4", 
  "https://www.youtube.com/watch?v=b1FinfVUp38", "https://www.youtube.com/watch?v=gnavcUHC6zc", "https://www.youtube.com/watch?v=YtSPQIK15uc", 
  "https://www.youtube.com/watch?v=X7cQ7KnoRk0", "https://www.youtube.com/watch?v=HUUwomMczeE", "https://www.youtube.com/watch?v=UwVVZPzo8iM", 
  "https://www.youtube.com/watch?v=deBdzC5QVQw", "https://www.youtube.com/watch?v=lelLVq8aA4I", "https://www.youtube.com/watch?v=IzTlPjgJfTk", 
  "https://www.youtube.com/watch?v=c9H7wwfrpgI", "https://www.youtube.com/watch?v=rKm24Z99hY8", "https://www.youtube.com/watch?v=XQFuZDueoEM", 
  "https://www.youtube.com/watch?v=hRFUZBXOWZI", "https://www.youtube.com/watch?v=9PA-F6ip9uY", "https://www.youtube.com/watch?v=fyrg_nLywUQ", 
  "https://www.youtube.com/watch?v=mf1ChkziFIQ", "https://www.youtube.com/watch?v=bbM8BmDcfCw", "https://www.youtube.com/watch?v=i6ZhgsdU0dE", 
  "https://www.youtube.com/watch?v=Tlwda9S58Lg", "https://www.youtube.com/watch?v=AUmL8xaj1ac", "https://www.youtube.com/watch?v=KUwUEPryqmw",
  "https://www.youtube.com/watch?v=RAyZM74lY3c", "https://www.youtube.com/watch?v=LdmyA3x0yb0", "https://www.youtube.com/watch?v=u2ExIOHzXO0", 
  "https://www.youtube.com/watch?v=Tg1KpGM9_gI", "https://www.youtube.com/watch?v=d7mrBC0zLZg", "https://www.youtube.com/watch?v=yEbdLlxqtyE&t=0s", 
  "https://www.youtube.com/watch?v=feMwFuihX2o", "https://www.youtube.com/watch?v=Wd2K0iVLNvM", "https://www.youtube.com/watch?v=V79JHBZuEh0", 
  "https://www.youtube.com/watch?v=kRTj6SDaqKQ", "https://www.youtube.com/watch?v=7btiHFnOqv4", "https://www.youtube.com/watch?v=g6cIYDvFS-U",
  "https://www.youtube.com/watch?v=MwUvx3p9U94", "https://www.youtube.com/watch?v=dNavpxx_PPk", "https://www.youtube.com/watch?v=JHKRL58WnFk", 
  "https://youtu.be/dY1eT3mPFpI", "https://youtu.be/7U3859AJiu4", "https://www.youtube.com/watch?v=ceiEEEPwbDU", 
  "https://www.youtube.com/watch?v=86LqlzZvkRI", "https://www.youtube.com/watch?v=CIZePAoYE9w", "https://www.youtube.com/watch?v=_4Zascmf2aw", 
  "https://www.youtube.com/watch?v=KoKPT_cnyXs", "https://youtu.be/CZgGSxYq_ww", "https://youtu.be/F01qYZmltuM", "https://youtu.be/v4gIq9CpfTk", 
  "https://www.youtube.com/watch?v=W-lrxHS9vZ4", "https://www.youtube.com/watch?v=688OPQ9WFpA", "https://www.youtube.com/watch?v=e579nO2lbjo", 
  "https://www.youtube.com/watch?v=E3C_x2l2Ds0", "https://youtu.be/ydk_pc-jx1c", "https://www.youtube.com/watch?v=Eywp61pXUm4", 
  "https://www.youtube.com/watch?v=aaEVHO_AVKs", "https://www.youtube.com/watch?v=OBWpzvJGTz4", "https://www.youtube.com/watch?v=OLBOn0Whhyc", 
  "https://www.youtube.com/watch?v=5LlQNty_C8s", "https://www.youtube.com/watch?v=KadcTafkJL0", "https://www.youtube.com/watch?v=Wlyq22ybsRw",
  "https://www.youtube.com/watch?v=DG5MfbXhnu4", "https://www.youtube.com/watch?v=CgHW02YF50s", "https://www.youtube.com/watch?v=9leJQpd512g", 
  "https://www.youtube.com/watch?v=en7JeZhL1Nw", "https://www.youtube.com/watch?v=tUf4nA4pYGk", "https://www.youtube.com/watch?v=YfGsngd7cZY", 
  "https://www.youtube.com/watch?v=tA8LjcpjjKQ", "https://www.youtube.com/watch?v=U0YBP1ve5rw", "https://www.youtube.com/watch?v=AkKiLaxXjAA", 
  "https://www.youtube.com/watch?v=AkKiLaxXjAA", "https://www.youtube.com/watch?v=aWXXA1p618c", "https://www.youtube.com/watch?v=eTMb2UkW4xY",
  "https://www.youtube.com/watch?v=688OPQ9WFpA", "https://www.youtube.com/watch?v=_neSA7J92dw", "https://www.youtube.com/watch?v=psxBizrPIxg",
  "https://www.youtube.com/watch?v=tdyybvuacVc", "https://www.youtube.com/watch?v=7f3DHfYNqwc", "https://www.youtube.com/watch?v=mJFcSNOzKdM",
  "https://www.youtube.com/watch?v=ggKeB9OOkRY", "https://www.youtube.com/watch?v=PsasZkQfskw", "https://www.youtube.com/watch?v=NJJZAshRF6A",
  "https://www.youtube.com/watch?v=OoogkKSFES0", "https://www.youtube.com/watch?v=zsUBRCdEDYY", "https://www.youtube.com/watch?v=NfbQTiW7kDY"];
  var len = options.length;
  var choice = Math.floor(Math.random() * options.length);
  msg.channel.send(`LOL\n${options[choice]}`);
  },
}
